import math

SCREEN = (SCREEN_HEIGHT ,SCREEN_WIDTH) = (720,720)

MAP_SIZE = 10
TILE_SIZE = int((SCREEN_HEIGHT)/MAP_SIZE)
MAX_DEPTH = int(MAP_SIZE*TILE_SIZE)

FOV = math.pi / 6
RAYS = 150
STEP_ANGLE = FOV / RAYS
SCALE = (SCREEN_HEIGHT) / RAYS

PLAYER_ANGLE = math.pi
PLAYER_X = SCREEN_HEIGHT / 2
PLAYER_Y = SCREEN_HEIGHT / 2

FORWARD = True

